layout_spectrum: 0.3189964
typography_spectrum: 0.4944315
color:
  saturation: 0.6218638
  brandStrength: 0.8286806
  lightness: 0.3763441
  rhythmicContrast: 0.562724
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Simulacra
